name : github-workflow
on : workflow_dispatch
jobs:
  format-json:
    runs-on : ubuntu-latest
    steps : 
      # - id : formatJson
      #   uses : fjogeleit/http-request-action@v1
      #   with : 
      #     url : 'https://jsonformatter.curiousconcept.com/process'
      #     method : 'POST'
      #     contentType : 'multipart/form-data'
      #     data : '{"data":{"Much JSON!":"So Wow!"},"jsontemplate":1,"jsonspec":4,"jsonfix":"on","version":2}'
      # - name : read Response
      #   run : |
      #     echo ${{ steps.formatJson.outputs.response }}
      
      # - id : fpl
      #   uses : fjogeleit/http-request-action@v1
      #   with : 
      #     url : 'https://fantasy.premierleague.com/api/bootstrap-static/'
      #     method : 'GET'
      # - name : read response as Json
      #   run : |
      #     echo ${{ steps.fpl.outputs.response }}

      - id : poll
        uses : manibharathi13/demo-javascript-action@First-Action
        with : 
          name : 'Mani Bharathi'
      - name : Display Response
        run : |
          echo ${{ steps.poll.outputs.response }}