name : github-workflow
on : workflow-dispatch
jobs:
  format-json:
    runs-on : ubuntu-latest
    steps : 
      -name : formatJson
       uses : fjogeleit/http-request-action@v1
       with : 
        url : 'https://jsonformatter.curiousconcept.com/process'
        method : 'POST'
        data : {
          data: {"Much JSON!":"So Wow!"},
          jsontemplate: 1,
          jsonspec: 4,
          jsonfix: on,
          autoprocess: ,
          version: 2
        }
      - name: Show Response
    run: |
      echo ${{ steps.formatJson.outputs.response }}
      